name: Node.js CI

on:
  pull_request:
    branches: [development]

jobs:
  checkdir:
    runs-on: self-hosted
    steps:
      - name: Full Checkout
        run: cd /root/green-apple-backend && git pull origin development

      - name: Install Dependencies
        run: cd /root/green-apple-backend && npm install

      - name: Run Tests
        run: cd /root/green-apple-backend && npm test
