name: Node.js CI

on:
  pull_request:
    branches: [development]

jobs:
  checkdir:
    runs-on: self-hosted
    steps:
      - name: print pwd
        run: pwd
      - name: list files
        run: ls -la
      - name: list files
        run: ls -la

