name: Green Apple Backend CI/CD

on:
  pull_request:
    branches: [development]

jobs:
  checkdir:
    runs-on: self-hosted
    steps:
      - name: Full Checkout
        run: cd /root/green-apple-backend && git pull origin development

      - name: Install Dependencies
        run: cd /root/green-apple-backend && npm install && npm run build

      - name: Making Build Directory
        run: cd /root/green-apple-backend && npm run building
        
      - name: Making Build Directory
        run: cd /root/green-apple-backend && mkdir build

      - run: ls
      - run: npm install
      - run: npm run format
      - run: npm run build --if-present
