name: Green Apple Backend CI/CD

on:
  push:
    branches: [development]

jobs:
  ciC:
    runs-on: self-hosted
    steps:
      - name: Pulling Code and Install Dependencies
        run: |
          cd /root/green-apple-backend &&
          (
            git stash &&
            git pull origin development
          ) &&
          (
             npm install &&

             npx prisma db push --accept-data-loss &&

            npm run build &&
            npm run format &&
            sudo pm2 list &&
            sudo pm2 restart 0
          )